### ISSUE TITLE
sqlalchemy required, but not documented

### ISSUE THREAD

**Issue by mrobbert** [CHPC-UofU/arbiter2#1]
I found that the arbiter service wasn't started on a new install of mine and traced it to the fact that it was trying to load the sqlalchemy module which wasn't installed. I looked again at the pip install that was mentioned in the documentation and setup.py and this module wasn't included there.

**Comment by dylngg** [comment]
Thanks for letting us know! I've noted that in the README and added a `requirements.txt` file for Python.
