### ISSUE TITLE
Documentation References to Gitlab

### ISSUE THREAD

**Issue by ellestad** [CHPC-UofU/arbiter2#11]
A lot of the documentation refers to a gitlab URL:

https://gitlab.chpc.utah.edu/arbiter2/arbiter2

Is that internal at utah.edu? It does not seem to be accessible.

Anytime I see that, should I just replace with the following?

https://github.com/CHPC-UofU/arbiter2

**Comment by jay-mckay** [comment]
Yes, we used to host it there. I will try to get the old references changed.

**Comment by ellestad** [comment]
Thanks!
