### ISSUE TITLE
BADNESS only ever triggers on mem and never on CPU usage

### ISSUE THREAD

**Issue by rokyo249** [chpc-uofu/arbiter2#13]
Hi,

I am using Arbiter2 on our user-facing desktop VMs to ensure that no single user takes away all CPU/mem for themselves.

The VMs are configured with 64 cores and 256GB RAM each and the Arbiter settings (in the status "normal") provide a cpu_quota of 3200 (32 cores) and a mem_quota of 64 (GB). The cpu_badness_threshold and mem_badness_threshold are both set to 0.5 with a time_to_max_bad of 600 (10 minutes).

According to the readme, I believed this should lead to BADNESS starting to accrue as soon as a user takes more than :

mem_badness_threshold * mem_quota (= 32GB)  of RAM
or
cpu_badness_threshold * cpu_quota (= 16 cores) of CPU.

However, when I simulate load with `stress`, only mem-overusage ever leads to BADNESS while cpu-overusage never does.

Running `stress -c 128 -m 64 --vm-bytes 1024M` (which should use 128 cores and 64GB of RAM) only shows 32 cores and roughly 30-40GB of RAM being used in `htop`.

Now, the limit to 32 cores comes from Arbiter2's cpu_quota which it can enforce through cgroups (which is not possible for mem), right? But the BADNESS never rises with constant use of 32 cores, even though cpu_badness_threshold is set to 0.5, so it should rise whenever more than 16 cores are constantly used (or am I getting this wrong?).

The memory BADNESS trigger works fine and BADNESS starts rising when `stress` uses 33-40 GB of RAM and falls off when it's just below 32 GB.

A typical line from the debug log in this situation reads:
```
24-09-12T10:49:31 - arbiter.triggers - DEBUG: 1000 (username) has nonzero badness: cpu=0.0, mem=20.59577248162693 since 2024-09-12T10:47:31
24-09-12T10:49:31 - arbiter.triggers - DEBUG: Whitelisted Usage: cpu 3193.921056092631, mem 13.22992468035479
```

I'm not sure if this is a bug or I missed something in the readme or my config is just wrong somewhere?

**Comment by mbruzek** [comment]
Greetings!

You mentioned you are using this for virtual machines (VMs).

Do you have "div_cpu_thresholds_by_threads_per_core = true" in your `etc/config.toml` file? I understand the default is false, but the [config.toml](https://github.com/chpc-uofu/arbiter2/blob/master/etc/config.toml) in the master branch, is configured "true".

The way I read the [CONFIG.md](https://github.com/chpc-uofu/arbiter2/blob/master/CONFIG.md#highusagewatcher-high_usage_watcher) file I would think a VM would set this to "false" because a VM has __virtual cores__ not physical ones like a real system.

**Comment by jay-mckay** [comment]
> You mentioned you are using arbiter on virtual machines (VMs).
> 
> Do you have "div_cpu_thresholds_by_threads_per_core = true" in your `etc/config.toml` file? I understand the default is false, but the [config.toml](https://github.com/chpc-uofu/arbiter2/blob/master/etc/config.toml) in the master branch, is configured "true".
> 
> The way I read the [CONFIG.md](https://github.com/chpc-uofu/arbiter2/blob/master/CONFIG.md#highusagewatcher-high_usage_watcher) file I would think a VM would set this to "false" because a VM has **virtual cores** not physical cores like a physical system.

This is correct - thresholds are calculated with regards to the kernel CPUs. You can see what CPUs are available with `lscpu` in your virtual machines - these are the CPUs Arbiter works with, and the thresholds should set accordingly. 

```24-09-12T10:49:31 - arbiter.triggers - DEBUG: Whitelisted Usage: cpu 3193.921056092631, mem 13.22992468035479```

Additionally, I see that the whitelisted usage is very high, meaning Arbiter is seeing the CPU usage but is not creating badness because the processes are whitelisted. What processes are in your whitelist? This is most likely the reason for not triggering on the CPU usage.

**Comment by rokyo249** [comment]
Hmm, the VM has assigned 64 cores (configured in Proxmox as: 1 socket, 64 cores) and `lscpu` also shows 64 CPUs.

The Badness paramters in Arbiter config are: 

```
max_history_kept = 180  # arbiter_refresh / history_per_refresh * 180 seconds of history for plots
cpu_badness_threshold = 0.45
mem_badness_threshold = 0.5
time_to_max_bad = 600  # 10 minutes
time_to_min_bad = 1800  # 30 minutes
```

I thought this would start accruing badness if >29 cores are used constantly. 

The normal status for a user has:

```
  [status.normal]
  cpu_quota = 3200  # 32 virtual cores
  mem_quota = 64  # Gigabyte
```

and these get halved for every level of penalty.

In the high usage watcher there is:

```
cpu_usage_threshold = 0.80
mem_usage_threshold = 0.80
div_cpu_thresholds_by_threads_per_core = true
```

And a whitelist is set under the heading [processes] and it contains: `whitelist = ['gcc', 'clang', 'cp', 'scp', 'rsync']`

Most of our users trigger high CPU by running Python scripts and it is not in the whitelist.

**Comment by jay-mckay** [comment]
@rokyo249 

I am starting to think this is an issue with the whitelist, but I will not be sure until I know some more. Would it be possible for you to provide your `config.toml` and some of the debug logs?

**Comment by rokyo249** [comment]
Sure, the `config.toml` is the following:

```
[general]
# Whether or not to actually email users and set quotas
debug_mode = false
# Arbiter will evaluate users for violations every 30s, with 3 points of information
arbiter_refresh = 30
history_per_refresh = 3
min_uid = 1000  # i.e. non-service accounts

[self]
# Arbiter's groupname (used for sudoers permissions and the --exit-file flag)
groupname = "root"

[badness]
# Change these to match your policy
max_history_kept = 180  # arbiter_refresh / history_per_refresh * 180 seconds of history for plots
cpu_badness_threshold = 0.45
mem_badness_threshold = 0.5
time_to_max_bad = 600  # 10 minutes
time_to_min_bad = 1800  # 30 minutes

[email]
email_domain = '---'  # Used for a generic email addr integration in integrations.py
from_email = '---'
admin_emails = []
#admin_emails = [---']
mail_server = '---'
keep_plots = false
plot_location = '../logs/%H/plots'  # %H means hostname, see special values. Make sure you create this directory before arbiter starts

[database]

[processes]
memsw = false
pss = true  # Requires CAP_SYS_PTRACE capability! See the install guide for info.
whitelist = ['gcc', 'clang', 'cp', 'scp', 'rsync']
whitelist_file = '../etc/whitelist.txt'

[status]
# A status group is selected by picking the first listed here that the user's uids or gids match.
order = ['invincible', 'admin', 'normal']
# If a user doesn't match into the status groups above, they land in the fallback status group
fallback_status = 'normal'
div_cpu_quotas_by_threads_per_core = true

  [status.normal]
  cpu_quota = 3200  # 32 virtual cores
  mem_quota = 64  # Gigabyte

  [status.admin]
  uids = [1000]
  # gids = [gid_of_admin, ]
  cpu_quota = 1600  # 16 virtual cores
  mem_quota = 64   # Gigabyte
  whitelist = ['bash', 'python', 'python3']

  [status.invincible]
  # If arbiter2.service has Slice=user-$ARBUID.slice (for turning on cgroups acct),
  # arbiter will be automatically tracked. You can tell arbiter to effectively
  # ignore itself by making itself invincible here.
  # uids = [$ARBUID]
  cpu_quota = 1e5
  mem_quota = 1e5   # Gigabyte

  [status.penalty]
  relative_quotas = false  # Note the relative_quotas, makes the *_quota less than 1
  order = ['penalty1', 'penalty2', 'penalty3']
  occur_timeout = 3600  # 1 hour

    [status.penalty.penalty1]
    timeout = 1800  # 30 mins
    cpu_quota = 1600
    mem_quota = 32
    expression = 'new'

    [status.penalty.penalty2]
    timeout = 1800
    cpu_quota = 800
    mem_quota = 16
    expression = 'repeated'

    [status.penalty.penalty3]
    timeout = 1800
    cpu_quota = 400
    mem_quota = 8
    expression = 'severe'

[high_usage_watcher]
high_usage_watcher = true
cpu_usage_threshold = 0.80
mem_usage_threshold = 0.80
timeout = 600  # warn at most every 10 minutes
div_cpu_thresholds_by_threads_per_core = true
user_count = 10
```


I just noticed while pasting this that `div_cpu_quotas_by_threads_per_core = true` is defined twice in the config: under [statuses] and under [high_usage_watcher]... I'll take one of them out.

**Comment by jay-mckay** [comment]
> I just noticed while pasting this that div_cpu_quotas_by_threads_per_core = true is defined twice in the config: under [status] and under [high_usage_watcher]... I'll take one of them out.

You should keep both of them (if `high_usage_watcher = true`), but they should match.

I will take a look at the config and see if I can spot any issues.

**Comment by rokyo249** [comment]
Thank you!

I also have this `whitelist.txt` that is included in the config, but it is just the standard one that ships with Arbiter2, no modification.

**Comment by jay-mckay** [comment]
The config looks OK, so I am still thinking the issue is with whitelists. Can you try running with no whitelist and see if anything changes? i.e.
```toml
[processes]
# ...
whitelist = []
whitelist_file = ''
# ...
[status.admin]
# ...
whitelist = []


```
