### ISSUE TITLE
Implement the email lookup code

### ISSUE THREAD

**Issue by mbruzek** [chpc-uofu/arbiter2#14]
In the [integrations.py](https://github.com/chpc-uofu/arbiter2/blob/master/etc/integrations.py) file, the doc_string on the `email_addr_of` method reads:
> Returns the email address of a user based on their uid or username using a
    post request to a server. If the lookup fails, None is returned.

But there is no lookup performed and None is not ever returned.

The default email of "username" + "@" + "domain" does not work for any of our users. 

I would like to look up our users in LDAP. The only way I know how to do that is to overwrite the integrations.py file. Could we make a class/module that allows users to provide their own implementation of the `email_addr_of` method?

**Comment by jay-mckay** [comment]
Hi, the intention of the `integrations.py` file is that it is to be overwritten. Feel free to modify `email_addr_of`, but just make sure the interface remains the same. See https://github.com/chpc-uofu/arbiter2/blob/master/INSTALL.md#integrating-things-a-bit-more for more details. Please let me know if you need any more help regarding this.

**Comment by mbruzek** [comment]
Hello jay-mckay,

I have already changed `integrations.py` to meet our needs with regard to LDAP. I feel bad about completely replacing the file, with different code. Is there any way this could be done with an interface so users could provide their own implementation of the interface?

**Comment by jay-mckay** [comment]
@mbruzek 

At our site we do not use the default `etc` directory, but rather pass in our own with the `--config` flag. Inside we have our `config.toml` and `integrations.py`, which are customized to our needs. When Arbiter starts up, it will load the configuration and add this integrations file to the Python path, and the original one is untouched. This works well for updating Arbiter, but it is not strictly necessary - I would not feel to bad about editing the code directly. 

As for an actual interface, this is something we are exploring with the newer version of Arbiter (under construction [here](https://github.com/chpc-uofu/arbiter)), so a admin can just import a function from anywhere to use. 

If you feel like adding a more explicit interface would be beneficial, feel free to describe just how it should work and we could get started on it, or better yet, submit a PR :).
