### ISSUE TITLE
memory usage goes undetected

### ISSUE THREAD

**Issue by rpmonti** [CHPC-UofU/arbiter2#3]
# Description

I have a couple of servers on which Arbiter is unable to grab the memory usage. The memory plot that is sent via email is blank, and if I take a good chunk of memory while touching very lightly on the cpu, it actually goes unnoticed by Arbiter, e.g.:

```
while :; do head -c2G /dev/zero | tail; done
```

Whereas all that has to do with cpu works fine.

I've been looking at `/sys/fs/cgroup/memory/user.slice/user-12345.slice/memory.stat`, and the value of `rss` doesn't seem to change, no matter what that user is doing.

I have another set of servers with similar characteristics on which Arbiter works flawlessly. Can you help me troubleshoot this? 

# Environment

```
# grep PRETTY /etc/os-release
PRETTY_NAME="CentOS Linux 7 (Core)"
# uname -r
3.10.0-1062.1.2.el7.x86_64
# systemctl --version
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN
# cat /proc/cmdline
BOOT_IMAGE=images/login-default-cluster-image/vmlinuz initrd=images/login-default-cluster-image/initrd  rdblacklist=nouveau ip=<...> BOOTIF=01-aa-bb-cc-dd-ee-ff
```

### Version
v2.1.0
### Using `--rhel7-compat`?
No
### arbiter.service
```
[Unit]
Description=Arbiter2
Documentation=https://gitlab.chpc.utah.edu/arbiter2/arbiter2
Wants=sendmail.service sssd.service network.target network-online.target
After=sendmail.service sssd.service network.target network-online.target

[Service]
User=arbiter
Slice=user-421.slice
CPUAccounting=true
MemoryAccounting=true

AmbientCapabilities=CAP_SYS_PTRACE

Type=simple
Environment=ARBITER_DIR=/opt/arbiter
WorkingDirectory=/opt/arbiter/arbiter
ExecStart=/opt/arbiter/arbiter_venv/bin/python ${ARBITER_DIR}/arbiter/arbiter.py -e ${ARBITER_DIR}/etc -g ${ARBITER_DIR}/etc/config.toml -s

Restart=on-failure
RestartPreventExitStatus=2


Environment=LD_LIBRARY_PATH=/cm/local/apps/python3/lib:$LD_LIBRARY_PATH

[Install]
WantedBy=multi-user.target
```
### etc/conf.toml
All defaults except email stuff.

**Comment by jay-mckay** [comment]
Hello. Would you mind running Arbiter in permissive mode, and sending me the debug logs? This is described [here.](https://github.com/CHPC-UofU/arbiter2/blob/master/INSTALL.md#testing-arbiter2-in-a-permissive-mode).

**Comment by rpmonti** [comment]
Hello Jay, thank you. Here's an excerpt: https://0x0.st/Hzo6.txt.

**Comment by jay-mckay** [comment]
It seems to me that arbiter is "seeing" some memory usage, might you try running a memory heavy application and seeing if that shows as well? The problem could be in the memory accounting strategy, i.e. PSS v.s. RSS.

**Comment by jay-mckay** [comment]
It should be noted that in permissive mode, Arbiter uses RSS, rather than RSS like you had enabled in your config.

**Comment by rpmonti** [comment]
It does not. `mem` value stays the same independently of actual memory usage by users. 

However I do manage to trigger memory detection (in debug mode) on another system, with same configuration and performing the same task:

```
(arbiter_venv) [root@sumner113 arbiter]# tail -f logs/sumner113/debug
23-02-28T10:00:03 - arbiter.statusdb - DEBUG: Badness table does not exist; creating it
23-02-28T10:00:03 - arbiter.statusdb - DEBUG: Status table does not exist; creating it
23-02-28T10:00:03 - arbiter.main - INFO: Failed to find statusdb database; created one at sqlite:///../logs/sumner113/statuses.db with status table 'status' and badness table 'badness'
23-02-28T10:00:03 - arbiter.logdb - INFO: Failed to find logdb database; creating one at ../logs/sumner113/log.2023-02-28.db
23-02-28T10:00:03 - arbiter.main - DEBUG: Initializing the collector with an interval of 30s, 3 history points and 2 polls per point (polls every 5.0s)
23-02-28T10:00:03 - arbiter.main - INFO: Will watch for high usage
23-02-28T10:00:03 - arbiter.main - INFO: Permissions and quotas won't be set since debug mode is on.
23-02-28T10:01:03 - arbiter.main - DEBUG: 63634 (polver) is new and has status: Status(normal/normal, occur=0, ts=, occur_ts=, authority=sumner113)
23-02-28T10:02:33 - arbiter.triggers - DEBUG: 63634 (polver) has nonzero badness: cpu=0.0, mem=10.0 since 2023-02-28T10:02:33
23-02-28T10:02:33 - arbiter.triggers - DEBUG: Whitelisted Usage: cpu 50.36715001986496, mem 0.0005822348512303757
23-02-28T10:02:33 - arbiter.triggers - DEBUG: Real Usage: cpu 75.6861568208076, mem 0.26839392002630036
23-02-28T10:03:03 - arbiter.triggers - DEBUG: 63634 (polver) has nonzero badness: cpu=0.0, mem=19.492406845092773 since 2023-02-28T10:02:33
23-02-28T10:03:03 - arbiter.triggers - DEBUG: Whitelisted Usage: cpu 74.45991861657313, mem 0.07061548184309548
23-02-28T10:03:03 - arbiter.triggers - DEBUG: Real Usage: cpu 102.79381172807778, mem 0.2516040700754005
```

**Comment by rpmonti** [comment]
Hi. A quick follow-up: it was something having to do with previous attempts to make use of cgroups on those specific systems. Restoring /etc/cgconfig.conf, /etc/cgrules.conf and /etc/cgsnapshot_blacklist.conf to their defaults, and disabling services cgred and cgconfig fixed it.
